app/src/Entity/Pack.php
<?php

namespace App\Entity;

use App\Repository\PackRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=PackRepository::class)
 */
class Pack
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="float")
     */
    private $price;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbStudents;

    /**
     * @ORM\Column(type="integer")
     */
    private $nbrProfessors;

    /**
     * @ORM\Column(type="boolean")
     */
    private $promotion;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $free_duration;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $type_duration;

    /**
     * @ORM\Column(type="float")
     */
    private $oldPrice;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="pack", orphanRemoval=true)
     */
    private $transtions;

    /**
     * @ORM\Column(type="string", length=255,nullable=true)
     */
    private $stripePrice;

    public function __construct()
    {
        $this->transtions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getPrice(): ?float
    {
        return $this->price;
    }

    public function setPrice(float $price): self
    {
        $this->price = $price;

        return $this;
    }

    public function getNbStudents(): ?int
    {
        return $this->nbStudents;
    }

    public function setNbStudents(int $nbStudents): self
    {
        $this->nbStudents = $nbStudents;

        return $this;
    }

    public function getNbrProfessors(): ?int
    {
        return $this->nbrProfessors;
    }

    public function setNbrProfessors(int $nbrProfessors): self
    {
        $this->nbrProfessors = $nbrProfessors;

        return $this;
    }

    public function getPromotion(): ?bool
    {
        return $this->promotion;
    }

    public function setPromotion(bool $promotion): self
    {
        $this->promotion = $promotion;

        return $this;
    }

    public function getFreeDuration(): ?int
    {
        return $this->free_duration;
    }

    public function setFreeDuration(?int $free_duration): self
    {
        $this->free_duration = $free_duration;

        return $this;
    }

    public function getTypeDuration(): ?string
    {
        return $this->type_duration;
    }

    public function setTypeDuration(?string $type_duration): self
    {
        $this->type_duration = $type_duration;

        return $this;
    }

    public function getOldPrice(): ?float
    {
        return $this->oldPrice;
    }

    public function setOldPrice(float $oldPrice): self
    {
        $this->oldPrice = $oldPrice;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTranstions(): Collection
    {
        return $this->transtions;
    }

    public function addTranstion(Transaction $transtion): self
    {
        if (!$this->transtions->contains($transtion)) {
            $this->transtions[] = $transtion;
            $transtion->setPack($this);
        }

        return $this;
    }

    public function removeTranstion(Transaction $transtion): self
    {
        if ($this->transtions->removeElement($transtion)) {
            // set the owning side to null (unless already changed)
            if ($transtion->getPack() === $this) {
                $transtion->setPack(null);
            }
        }

        return $this;
    }

    public function getStripePrice(): ?string
    {
        return $this->stripePrice;
    }

    public function setStripePrice(string $stripePrice): self
    {
        $this->stripePrice = $stripePrice;

        return $this;
    }
}

app/templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
        <script src="https://js.stripe.com/v3/"></script>
        {% block stylesheets %}
            {{ encore_entry_link_tags('app')}}
        {% endblock %}
        <style>

            #card-element {
                width: 100%;
            }

            .switch {
                position: relative;
                display: inline-block;
                width: 60px;
                height: 34px;
            }

            .switch input {
                opacity: 0;
                width: 0;
                height: 0;
            }

            .slider {
                position: absolute;
                cursor: pointer;
                top: 0;
                left: 0;
                right: 0;
                bottom: 0;
                background-color: #ccc;
                -webkit-transition: .4s;
                transition: .4s;
            }

            .slider:before {
                position: absolute;
                content: "";
                height: 26px;
                width: 26px;
                left: 4px;
                bottom: 4px;
                background-color: white;
                -webkit-transition: .4s;
                transition: .4s;
            }

            input:checked + .slider {
                background-color: #2196F3;
            }

            input:focus + .slider {
                box-shadow: 0 0 1px #2196F3;
            }

            input:checked + .slider:before {
                -webkit-transform: translateX(26px);
                -ms-transform: translateX(26px);
                transform: translateX(26px);
            }

            /* Rounded sliders */
            .slider.round {
                border-radius: 34px;
            }

            .slider.round:before {
                border-radius: 50%;
            }

        </style>
    </head>
    <body>
        {{ include('partials/_nav.html.twig')}}
        <div class="flash-message-section">
            {{ include('partials/_flash_messages.html.twig')}}
        </div>
        
        <div class="main-container container-fluid">
            {% block body %}{% endblock %}
            {{ include('partials/_conversation.html.twig') }}
        </div>

        {{ include('partials/_footer.html.twig') }}
        {% block javascripts %}
            {{ encore_entry_script_tags('app')}}
        {% endblock %}
    </body>
</html>

app/templates/home.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome!{% endblock %}

{% block body %}

    <div class="home-container container-fluid">
        <div class="row">
            <div class="col-lg-6 home-left-side">
                <div class="home-left-image">
                    <img src="{{asset('build/images/image_home5.png')}}" alt="home image for illustration" class="home-image"></img>
                </div>
            </div>
            <div class="col-lg-5 home-right-side">
                <div class="w-75">
                    <div>
                        <h1 class="display-6 mb-3">EXERCISE IN A FUN WAY</h1>
                        <hr>
                        <p>Our platform allows the management of students and teachers, and includes an online exercise creation tool whether it is qcm, free answer or even computer code.<br />
                        You are a school structure and this tool corresponds perfectly to your needs ?<br />
                        So don't hesitate and subscribe to one of our offers to take advantage of it now.</p>
                    </div>
                    <div class="home-offers-button"><a href="{{ path('packs') }}">DISCOVER OUR OFFERS</a></div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

app/templates/home_pack.html.twig
{% extends 'base.html.twig' %}

{% block title %}Welcome!{% endblock %}

{% block body %}

    <div class="text-center main-title-page mb-5">
        <h1 class="display-5 font-weight-bold">All our offers</h1>
        <hr>
    </div>

    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="card-deck col-md-10" style="color:black;">
                {% for offre in offres %}
                    <div class="col-lg-3 col-md-6 col-sm-12 px-0 py-2">
                        <div class="card border-light">
                            <div class="banner-promotion mb-3">
                                {% if offre.promotion %}
                                    <p class="banner-text text-center h-100 font-weight-bold h5">Good deal</p>
                                {% endif %}
                            </div>
                            <div class="card-header card-pack">
                                <h2 class="display-5">{{ offre.name | capitalize }}</h2>
                            </div>
                            <div class="card-body border shadow-lg p-4">
                                <div class="card-text">
                                    <div class="price">
                                        <p class="font-weight-bold">Price</p>
                                        <p class="font-weight-bold h4 text-center"> {{ offre.price }} € / Month</p>
                                    </div>
                                    {% if offre.promotion %}
                                        <div class="promotion">
                                            <small>for {{ offre.freeDuration }} {{ offre.typeDuration }} then {{ offre.oldPrice }} €</small>
                                        </div>
                                    {% endif %}
                                    <hr>
                                    <div class="people">
                                        <p class="font-weight-bold">Limits</p>
                                        <ul>
                                        <li>up to {{ offre.nbstudents }} students</li>
                                        <li>up to {{ offre.nbrProfessors }} professors</li>
                                        </ul>
                                    </div>
                                    <hr>
                                </div>
                                <div class="buy-button w-100">
                                    <a href="{{ path('admin_payment_index',{'pack': offre.id})}}"><button class="btn btn-warning w-50 my-3 rounded-pill">Acheter</button></a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

{% endblock %}